# Generated by Django 5.0.2 on 2024-02-29 21:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_capital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(default='No description')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAccToAcc',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nexus_capital.transaction')),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='nexus_capital.account')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='nexus_capital.account')),
            ],
            bases=('nexus_capital.transaction',),
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
