# Generated by Django 5.0.2 on 2024-03-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_capital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
